SUBNET_RANGES = (
    (10, 0, 0, 0, 8),
    (172, 16, 0, 0, 12),
    (192, 168, 0, 0, 16),
)

THREAT_LEVELS = ("None", "Low", "Medium", "High", "Critical")

SUSPICIOUS_PORTS = {4444, 1337, 31337, 6666, 6667, 8087, 9090, 9999}

BRUTEFORCE_PORTS = {21, 22, 23, 3389, 3306, 1433}

BEACON_MIN_PACKETS = 4
BEACON_MIN_INTERVALS = 3
BEACON_CV_THRESHOLD_REGULAR = 0.1
BEACON_CV_THRESHOLD_SUSPICIOUS = 0.3
BEACON_SIZE_CV_THRESHOLD = 0.15
BEACON_REGULARITY_HIGH = 0.85
BEACON_REGULARITY_MEDIUM = 0.6
BEACON_SIZE_REGULARITY_HIGH = 0.9
BEACON_SIZE_REGULARITY_MEDIUM = 0.7
BEACON_DURATION_SHORT = 60
BEACON_DURATION_LONG = 300
BEACON_CONFIDENCE_THRESHOLD = 0.5

DNS_MIN_QUERIES = 3
DNS_LENGTH_ANOMALOUS = 120
DNS_LENGTH_SUSPICIOUS = 80
DNS_ENTROPY_THRESHOLD = 3.5
DNS_UNIQUE_QUERY_THRESHOLD = 5
DNS_QUERY_COUNT_THRESHOLD = 10
DNS_CONFIDENCE_THRESHOLD = 0.4

PORT_SCAN_MIN_PACKETS = 5
PORT_SCAN_UNIQUE_PORT_THRESHOLD = 10
PORT_SCAN_SYN_RATIO_THRESHOLD = 0.7
PORT_SCAN_RATE_THRESHOLD = 2.0
PORT_SCAN_HIT_SERVICES_THRESHOLD = 3
PORT_SCAN_SYN_ONLY_RATIO = 0.9
PORT_SCAN_CONFIDENCE_THRESHOLD = 0.4

ICMP_MIN_PACKETS = 3
ICMP_PAYLOAD_ANOMALOUS = 150
ICMP_PAYLOAD_SUSPICIOUS = 100
ICMP_RATE_THRESHOLD = 1.0
ICMP_UNIQUE_SIZES_THRESHOLD = 2
ICMP_MIN_PACKETS_FIXED = 5
ICMP_CONFIDENCE_THRESHOLD = 0.4

PAYLOAD_MIN_PACKETS = 2
PAYLOAD_UPLOAD_RATIO_THRESHOLD = 0.85
PAYLOAD_UPLOAD_BYTES_THRESHOLD = 5000
PAYLOAD_HTTP_AVG_SIZE = 1000
PAYLOAD_UNIQUE_SIZE_THRESHOLD = 3
PAYLOAD_MIN_PACKETS_FIXED = 8
PAYLOAD_CONFIDENCE_THRESHOLD = 0.3

IDS_MIN_SUSPICIOUS_SCORE = 0.1
IDS_AGGREGATION_WINDOW_THRESHOLD = 20
IDS_BEACON_DURATION_LONG = 60
IDS_BEACON_PKT_STD_LOW = 30
IDS_BEACON_PKT_STD_VLOW = 10
IDS_BEACON_SCORE_DEFAULT = 0.6
IDS_BEACON_SCORE_HIGH = 0.9

ZEEK_ANOMALY_THRESHOLD = 0.25
ZEEK_BASELINE_PCT_THRESHOLD = 0.99
